#!/bin/bash
set -euo pipefail

MARKER_FILE="$HOME/.config/rakuos/.firstrun-done"

mkdir -p "$(dirname "$MARKER_FILE")"

if [ ! -f "$MARKER_FILE" ]; then

    # Create symlink safely
    if [ ! -e "$HOME/.icons" ]; then
        ln -s "$HOME/.local/share/icons" "$HOME/.icons"
    fi

    # Setup Initial Flatpak Overrides
    OVERRIDE="$HOME/.local/share/flatpak/overrides/global"
    mkdir -p "$(dirname "$OVERRIDE")"

    cat > "$OVERRIDE" <<'EOF'
[Context]
filesystems=xdg-config/gtk-3.0:ro;xdg-data/applications;~/.var/app/io.github.benjamimgois.goverlay/data/goverlay;xdg-config/gtk-4.0:ro;/var/mnt;xdg-config/vkBasalt:create;/mnt;xdg-run/.flatpak/com.discordapp.Discord:create;~/.themes;~/.icons;/home;/var/home;xdg-data/icons;xdg-desktop;xdg-config/MangoHud:create;

[Environment]
VK_INSTANCE_LAYERS=VK_LAYER_MANGOHUD_overlay_x86_64
EOF

    touch "$MARKER_FILE"
fi

# Sync system themes so flatpak has access
SYSTEM_THEMES="/usr/share/themes"
USER_THEMES="$HOME/.themes"

mkdir -p "$USER_THEMES"

rsync -a --copy-links \
  --exclude="Clearlooks" \
  --exclude="Crux" \
  --exclude="HighContrast" \
  --exclude="Industrial" \
  --exclude="Mist" \
  --exclude="Raleigh" \
  --exclude="ThinIce" \
  "$SYSTEM_THEMES/" "$USER_THEMES/"

# Set the correct permissions for the user directory 
echo "Setting correct permissions for $USER_THEMES..." 
chown -R "$USER:$USER" "$USER_THEMES"

echo "RakuOS user setup complete."
